name: 'storage-destroy'

on:
  workflow_dispatch:

env:
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -upgrade -var-file="dev.tfvars"
        working-directory: ./storage

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars" -input=false
        working-directory: ./storage

      - name: Terraform Destroy
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
        working-directory: ./storage
