name: 'storage'

on:
  push:
    branches: ['feature/poc']

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - uat

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }} # Default to dev for push

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Debug
        run: |
          echo "Github: ${{ toJson(github) }}"
          echo "Environment: ${{ env.DEPLOY_ENV }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "s:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./storage

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./storage

      - name: Azure Login
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: false
          environment: azurecloud
          audience: api://AzureADTokenExchange

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: az account show

      - name: Terraform Plan
        working-directory: ./storage
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform plan -var-file=${{ env.DEPLOY_ENV }}.tfvars -input=false

      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        run: terraform apply -var-file=${{ env.DEPLOY_ENV }}.tfvars -auto-approve -input=false
        working-directory: ./storage
